repos:
  # - repo: https://github.com/rbubley/mirrors-prettier
  #   rev: 787fb9f542b140ba0b2aced38e6a3e68021647a3 # frozen: v3.5.3
  #   hooks:
  #     - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # frozen: v1.37.1
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: d7a4f7cf4914d3bffb9b83bdbc45fd2a00c91ff9  # frozen: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

ci:
  autoupdate_schedule: monthly
